### PR TITLE
rich video previews in the sidebar

### PR DESCRIPTION
**Pull request by icewind1991**
Before: 

After:

cc @jancborchardt @MorrisJobke

### CODE REVIEW

**Comment by jospoortvliet** [comment]
super cool :D

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by jancborchardt** [comment]
This is damn awesome @icewind1991! :) Similar as to PDF, is this not suitable for a possible grid view, or is it? ;)

**Comment by icewind1991** [comment]
It is not

**Comment by jancborchardt** [comment]
Dayum. Let’s check it out for Nextcloud 12 maybe ;)

**Comment by MorrisJobke** [comment]
I guess we need to revert this one again: https://github.com/nextcloud/server/issues/2557

**Comment by icewind1991** [comment]
I guess :(

**Pull request merged**
