### PR TITLE
Update viewer.js

### PR DESCRIPTION
**Pull request by tobilap**
Fixing the Loading of video JS , I'm not a pro in JS but it works :)

### CODE REVIEW

**Comment by LukasReschke** [comment]
Fixes https://github.com/nextcloud/files_videoplayer/issues/25

**Comment by LukasReschke** [comment]
Thanks! Cherry-picked to stable12 with https://github.com/nextcloud/files_videoplayer/commit/91fab5f89bf5cf6d018638758b80e9fc88a71b45

**Comment by MarkusLange** [comment]
Thanks, but it doesn't arrived in the final/latest zip and tar.bz2 from 12

**Comment by LukasReschke** [comment]
It will be included in 12.0.1

**Pull request merged**
