### PR TITLE
fix url encoding

### PR DESCRIPTION
**Pull request by Instagit**
Fix an issue with the [URL encoding](https://github.com/owncloud/files_videoplayer/issues/63) and two syntax/comment improvements.

### CODE REVIEW

**Comment by Instagit** [comment]
@nextcloud/javascript

**Comment by skjnldsv** [comment]
Seems good to me! :+1:

**Comment by MorrisJobke** [comment]
Hi @Instagit - we require the sign-off being in the commit. See https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work

it may be better to do a cherry pick to credit Thomas' work here. Just add the OC remote repo to the same repo and fetch from there. Then do a cherry pick of Thomas' commit ;)

Thanks 👍 It works here

**Comment by Instagit** [comment]
Do I sign the cherry picked commit, too?

**Comment by MorrisJobke** [comment]
> Do I sign the cherry picked commit, too?

Yep. It's that you checked the license of this code to be compliant to our license - roughly ;)

**Pull request closed without merging**
