### PR TITLE
Fill screen in fullscreen mode for public videos. Fixes #77

### LINKED ISSUE #77: Video doesn't scale in fullscreen (public video share)
### Expected behaviour
In fullscreen mode, video scales across the whole display.

### Actual behaviour
Video doesn't scale, screen is filled with black around the video content instead.

### Steps to reproduce
1. Click the fullscreen icon
2. Observe the error
3. cry

Nextcloud 15.0.0
Video player 1.4.0
Error is present in latest Chrome, latest FF, IE 11. Windows and Linux (OSX wasn't tested)
Other players based on video.js behave as expected.
screenshot : https://i.imgur.com/I7nxHDZ.png

### PR DESCRIPTION
**Pull request by pjrobertson**
Tested on: Chrome 71, Firefox 57, Safari 12

### CODE REVIEW

**Comment by lsde** [comment]
LGTM, cherry-picked the commit and fixes the problem in production for all users.
Let's get it merged soon!

**Comment by juliushaertl** [comment]
Thanks a lot for your contribution @lsde 

There is only one thing missing - you need to add a sign-off message to the commits you made. Read more about this in https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work

**Comment by lsde** [comment]
@juliushaertl well I'm not the author of the code, I only reported the original bug #77
@pjrobertson is the author of the patch

**Comment by pjrobertson** [comment]
@juliushaertl let me know if you want me to sign off and force-push. Sign off message:

Otherwise, sign off message:

`Signed-off-by: Patrick Robertson <robertson.patrick@gmail.com>`

**Pull request merged**
