### PR TITLE
Fix removed global function call to escapeHTML

### PR DESCRIPTION
**Pull request by MorrisJobke**
nextcloud/server#19357

* share a video by public link
* open link
* expected: a video player is shown
* actual: no video player is shown and an error about missing `escapeHTML` is printed

@skjnldsv @ChristophWurst Mind to compile this and add a commit with the new assets here, because I'm currently fixing my local npm environment. At least this should fix it. 🙈

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> @skjnldsv @ChristophWurst Mind to compile this and add a commit with the new assets here, because I'm currently fixing my local npm environment. At least this should fix it. 🙈

Managed to compile it now :)

Works locally.

**Comment by MorrisJobke** [comment]
> Managed to compile it now :)

Seems to build slightly different on my machine and here. Let's build it then here.

**Pull request merged**
