### PR TITLE
Js cleanup and mkv support

### PR DESCRIPTION
**Pull request by icewind1991**
- don't load videojs every time we hide and re-show the player
- more efficient jquery usage
- support playing mkv files

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Instagit can you review this? :)

**Comment by Instagit** [comment]
Some good optimizations. :) About this commit:

add support for mkv playback in chrome ee8eb99
>// chrome is a little kid that refuses to play mkv if it knows it's an mkv, webm uses the same container format

WebM is a subset of MKV. What happens when an MKV file uses features that are not supported by WebM? And what happens when you try to play an MKV in other browsers with this hack?

If it doesn't cause anything to break it should be good.

**Comment by jancborchardt** [comment]
A cross-review by @nextcloud/javascript please ;)

**Comment by icewind1991** [comment]
> WebM is a subset of MKV. What happens when an MKV file uses features that are not supported by WebM? And what happens when you try to play an MKV in other browsers with this hack?

From my testing this doesn't change anything for other browsers, if chrome is unable to playback the mkv it will show the generic "cant play this file" widget afaik

**Comment by MorrisJobke** [comment]
Code changes look good and mkv playback works 👍

**Comment by dzymail** [comment]
is this fixed? 
i can played a mkv file but no sound, mp4 file is fine. (nextcloud 11 on Debian server)

**Comment by Instagit** [comment]
Could you provide information about the file that doesn't work? Browsers don't have full MKV support and there will probably be files that can't be played. I suppose multiple audio streams or something like that could be a problem. If you can install ffmpeg:

    ffmpeg -i FILENAME

**Comment by dzymail** [comment]
My server does not have public network ip now. I tested multiple files, no one has sound. but I tested these files on other business server is ok.

**Comment by dzymail** [comment]
after update to 11.0.1, all working good. dont know what happened   :)  
last thing is no button for control playback speed.

**Pull request merged**
