### PR TITLE
Fix 18 public folder

### PR DESCRIPTION
**Pull request by skjnldsv**
Important fix, somehow we changed something and `FileActions` is not here.
This fixes the opening of videos in a public shared folder

### CODE REVIEW

**Comment by Aurnytoraink** [comment]
When it will be updated ?

**Comment by skjnldsv** [comment]
Next release

**Comment by klaasvakie** [comment]
This problem re-appeared for me after the snap update (to 18.0.4) this morning. Video player works perfectly well when logged in. On a public share I just see the spinner.

**Comment by Walterfilms** [comment]
hello klaasvakie, 

I've run into the same issues as you, but it seems like the public sharing with videos is now handled with viewer app, which is integrated into nextcloud directly.

I've been searching all day as to why it was broken again, and found a very strange workaround...

as admin in "settings", 

in "sharing" page and then "federated cloud sharing" section

if the option "Allow users on this server to send shares to other servers" is not checked...

than the video player doesn't work on public sharing...

this is absolutly non-sense as i don't use federated servers, but somehow when comparing why it worked on some instances and not on the one i needed it the most, i discovered this.

let me know if it worked for you too

have a nice day,

**Comment by klaasvakie** [comment]
Wow @Walterfilms, no idea how you found that! But yes, it does fix the problem for me as well, thank you very much for your sleuthing.

So @skjnldsv, should I file a new bug specifically around the federated sharing toggle, or are you happy to pick it up from here?

**Comment by skjnldsv** [comment]
> So @skjnldsv, should I file a new bug specifically around the federated sharing toggle, or are you happy to pick it up from here?

Hey! :)
There is already an issue about this here: https://github.com/nextcloud/server/issues/20132

**Comment by klaasvakie** [comment]
Looks like that bug pretty much describes what I'm seeing so I'm not going to add more noise. Thanks for the help @skjnldsv!.

**Comment by maidstein** [comment]
@Walterfilms Thanks so much!

**Comment by freumichCH** [comment]
Grate Work @Walterfilms

**Pull request merged**
