### PR TITLE
Use videoplayer also on public sharing pages

### LINKED ISSUE #48: Use videoplayer on public pages
We should also use the video.js player from this app when a video is shared though a public link. No need to have a separate logic for presenting the video file in the server.

That would also fix https://github.com/nextcloud/server/issues/763

### PR DESCRIPTION
**Pull request by juliushaertl**
- Use the video player in an overlay on public shared folders
- Use the video player inline for shared video files

fixes #48

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I would increase a bit the size of the initial container, because it looks weird during loading:

bildschirmfoto 2018-01-22 um 16 22 12

Also then the error message would be a lot more readable:

bildschirmfoto 2018-01-22 um 16 23 48

**Comment by Instagit** [comment]
Nice. Thank you juliushaertl!

I think click to play for videos is mostly managed by browsers now anyway as they continue to restrict autoplay.

See [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

**Comment by juliushaertl** [comment]
Hm, I guess we should probably still remove the autoplay for browsers that don't enforce click to play. I'll add that to a follow-up PR with the nitpicks form @MorrisJobke

**Comment by jospoortvliet** [comment]
Nice work 👍

**Pull request merged**
