### PR TITLE
Ignore query arguments in single video share

### PR DESCRIPTION
**Pull request by rullzer**
Else the url is not constructed properly

Fixes: https://github.com/nextcloud/server/issues/14477

### CODE REVIEW

**Comment by shubhank008** [comment]
@rullzer my nextcloud 15 install doesn't seem to have the file called main.js and/or by when will you be pushing this as a update in the main app ?

**Comment by rullzer** [comment]
this will ship with NC16

**Comment by shubhank008** [comment]
@rullzer okay, means cannot apply as a manual fix in NC15 yet ? Also, I think this still does not fix the video url being broken on public share page (query string ?aa=bb still attached), which I think is taking url from here:  
``` videoViewer.location = data.fileList.getDownloadUrl(file, videoViewer.dir); ```

**Comment by ChristophWurst** [comment]
You might have success applying the patch at https://github.com/nextcloud/files_videoplayer/blob/stable15/js/viewer.js#L150.

**Comment by shubhank008** [comment]
@rullzer Tried applying it but doesn't work, as I mentioned, it's not fixing the public shared link's video playback being broken, as its picking the video URL from the above mentioned code line (also part of viewer.js).

**Comment by Ciangi** [comment]
Hello,

i have the latest version of Nextcloud - 16.0.3
I have still problem with open mp4 video from shared public link.
The problem occurs in Chrome and Firefox - on Edge is fine.

Scenario:
I shared public link with some directory.
This directory contains 2 sub dirs.
when i enter to one of this sub dirs and try to open mp4 video file i got error that can't open it. ( The same like in nextcloud/server#14477 )

Thank you for any help.

**Pull request merged**
